version: '3.8'

services:
  # MySQL服务
  mysql:
    image: mysql:8.0
    container_name: yymall-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: yymall_user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - yymall-network

  # Redis服务
  redis:
    image: redis:6.2
    container_name: yymall-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - yymall-network

  # Consul服务
  consul:
    image: consul:latest
    container_name: yymall-consul
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    networks:
      - yymall-network

  # Nacos服务
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: yymall-nacos
    restart: always
    environment:
      - MODE=standalone
      - JVM_XMS=512m
      - JVM_XMX=512m
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    networks:
      - yymall-network

  # Jaeger服务
  jaeger:
    image: jaegertracing/all-in-one:1.49
    container_name: yymall-jaeger
    restart: always
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - yymall-network
      
networks:
  yymall-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: 